name: Windows release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CMake and dependencies
        run: |
          choco install cmake --confirm
        shell: powershell

      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure, Build, and Package
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles"
          cmake --build build --config Release
          Remove-Item -Recurse -Force build
