name: Linux build

on:
  workflow_dispatch:
  push:
    branches: [ main, actions-setup ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CMake and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-10 gcc-10 cpp-10 libasound2-dev mesa-common-dev libx11-dev \
            libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev libopenal-dev \
            libdwarf-dev libdw-dev binutils-dev
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-10 \
            --slave /usr/bin/gcov gcov /usr/bin/gcov-10
          g++ --version
          cmake --version

      - name: Configure, Build, and Package
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON
          cmake --build build --config Release -j "$(nproc)"
          rm -rf build
